owner: Cascadia-Web-Services
repo: monitoring

sites:
  - name: Cascadia Web Services - Website
    url: https://cascadiaweb.services

status-website:
  cname: status.cascadiaweb.services
  logoUrl: https://cascadiaweb.services/wp-content/uploads/2023/08/Logo-White-Border-scaled.webp
  name: Cascadia Web Services
  theme: night
  navbar:
    - title: Back to Website
      href: https://cascadiaweb.services

i18n:
  footer: This is an independent monitoring resource powered though GitHub and by Upptime.
