# Change these first
owner: Cascadia-Web-Services # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Casacadia Web Services
    url: https://cascadiaweb.services

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cascadiaweb.services
  # baseUrl: /your-repo-name
  logoUrl: https://cascadiaweb.services/wp-content/uploads/2023/08/Logo-White-Border-scaled.webp
  name: CWS Uptime Montioring
  introTitle: "Helping You Reach New Heights"
  theme: dark
  navbar:
    - title: Back to Website
      href: https://cascadiaweb.services
  i18n:
    footer: 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
